# Generated by Django 5.1.4 on 2024-12-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.AlterModelTable(
            name='event',
            table='Home_event',
        ),
    ]
