# Generated by Django 5.1.4 on 2024-12-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_remove_profile_bio_alter_event_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/Generic avatar.png', null=True, upload_to='profile_pics/'),
        ),
    ]
